export const SET_USERID = 'SET_USERID'

export const SET_USERINFO = 'SET_USERINFO'

export const SET_USERINIT = 'SET_USERINIT'

export const SET_SMSCODE = 'SET_SMSCODE'

export const SET_ADDRESS = 'SET_ADDRESS'

export const SET_ADDRESS_RES = 'SET_ADDRESS_RES'

export const SET_SEND = 'SET_SEND'

export const SET_QR_SEND = 'SET_Qr_SEND'

export const SET_SEND_SWITCH = 'SET_SEND_SWITCH'

export const SET_SEND_ADD = 'SET_SEND_ADD'

export const SET_SEND_RES = 'SET_SEND_RES'

export const SET_SEND_DEFAULTADDRESS = 'SET_SEND_DEFAULTADDRESS'

export const SET_SITE = 'SET_SITE'

export const SET_SITE_RECENT = 'SET_SITE_RECENT'

export const SET_PICKUP_SIGN = 'SET_PICKUP_SIGN'

export const SET_PICKUP_WAIT = 'SET_PICKUP_WAIT'

export const SET_OPENID = 'SET_OPENID'

export const SET_PACKAGE_PICKUP = 'SET_PACKAGE_PICKUP'

export const SET_PACKAGE_SEND = 'SET_PACKAGE_SEND'

export const SET_PACKAGE_TYPE = 'SET_PACKAGE_TYPE'
